CREATE TABLE Clients (
	client_id SERIAL PRIMARY KEY,
	client_name VARCHAR(50) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	phone VARCHAR(20) UNIQUE NOT NULL,
	notes VARCHAR(200),
	status BOOLEAN DEFAULT FALSE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

